-- Click Mais OS Fase 1 / F1.4
-- Seed deterministic catalog from approved Fase 0 v1.2.1 source.
-- Generated from 01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI; no conversational prices.

insert into catalog.pricing_tiers (code,pix_base,source_version)
values
('T1190',1190.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'),
('T1290',1290.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'),
('T1390',1390.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'),
('T1490',1490.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'),
('T1590',1590.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'),
('T1690',1690.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'),
('T1790',1790.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'),
('T1890',1890.00,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI')
on conflict (code) do update
set pix_base=excluded.pix_base,
    source_version=excluded.source_version,
    updated_at=now();

insert into catalog.services
  (code,official_name,category,active,quoteable_automatically,details_json,source_version)
values
  ('cabine_fotos','Cabine de Fotos','main',true,true,'{}'::jsonb,'fase0-v1.2.1'),
  ('totem_fotos','Totem de Fotos','main',true,true,'{}'::jsonb,'fase0-v1.2.1'),
  ('set_fotografico','Set Fotográfico','main',true,true,'{}'::jsonb,'fase0-v1.2.1'),
  ('plataforma_360','Plataforma 360','main',true,true,'{}'::jsonb,'fase0-v1.2.1'),
  ('fotografo_evento','Fotógrafo para evento','main',true,true,'{}'::jsonb,'fase0-v1.2.1'),
  ('album_assinaturas','Álbum de Assinaturas','addon',true,true,'{"fixed_pix":300}'::jsonb,'fase0-v1.2.1'),
  ('painel_fotografico_2x1','Painel Fotográfico 2x1','addon',true,false,'{"pricing":"human_required"}'::jsonb,'fase0-v1.2.1'),
  ('drop_box_octogonal','Drop Box Octogonal','addon',true,false,'{"pricing":"human_required"}'::jsonb,'fase0-v1.2.1')
on conflict (code) do update
set official_name=excluded.official_name,
    category=excluded.category,
    active=excluded.active,
    quoteable_automatically=excluded.quoteable_automatically,
    details_json=excluded.details_json,
    source_version=excluded.source_version,
    updated_at=now();

with src(canonical_name,normalized_name,tier_code,status,notes) as (
  values
('brás cubas','bras cubas','T1190','active',null),
('jundiapeba','jundiapeba','T1190','active',null),
('mogi das cruzes','mogi das cruzes','T1190','active',null),
('quatinga','quatinga','T1190','active',null),
('sabaúna','sabauna','T1190','active',null),
('arujá','aruja','T1290','active',null),
('biritiba mirim','biritiba mirim','T1290','active',null),
('biritiba ussu','biritiba ussu','T1290','active',null),
('taiaçupeba','taiacupeba','T1290','active',null),
('boa vista paulista','boa vista paulista','T1390','active',null),
('cidade kemel','cidade kemel','T1390','active',null),
('cidade tiradentes','cidade tiradentes','T1390','active',null),
('ferraz de vasconcelos','ferraz de vasconcelos','T1390','active',null),
('guaianases','guaianases','T1390','active',null),
('guararema','guararema','T1390','active',null),
('itaquaquecetuba','itaquaquecetuba','T1390','active',null),
('poá','poa','T1390','active',null),
('santa margarida paulista','santa margarida paulista','T1390','active',null),
('santo antônio paulista','santo antonio paulista','T1390','active',null),
('suzano','suzano','T1390','active',null),
('vila curuçá','vila curuca','T1390','active',null),
('artur alvim','artur alvim','T1490','active',null),
('bertioga','bertioga','T1490','active',null),
('cangaíba','cangaiba','T1490','active',null),
('capuava','capuava','T1490','active',null),
('carrão','carrao','T1490','active',null),
('cidade líder','cidade lider','T1490','active',null),
('ermelino matarazzo','ermelino matarazzo','T1490','active',null),
('guarulhos','guarulhos','T1490','active',null),
('igaratá','igarata','T1490','active',null),
('itaim paulista','itaim paulista','T1490','active',null),
('itaquera','itaquera','T1490','active',null),
('jacareí','jacarei','T1490','active',null),
('jardim helena','jardim helena','T1490','active',null),
('jardim presidente dutra','jardim presidente dutra','T1490','active',null),
('jardim santa luzia','jardim santa luzia','T1490','active',null),
('josé bonifácio','jose bonifacio','T1490','active',null),
('lajeado','lajeado','T1490','active',null),
('mauá','maua','T1490','active',null),
('nossa senhora do remédio','nossa senhora do remedio','T1490','active',null),
('ouro fino paulista','ouro fino paulista','T1490','active',null),
('palmeiras','palmeiras','T1490','active',null),
('penha','penha','T1490','active',null),
('ponte rasa','ponte rasa','T1490','active',null),
('ribeirão pires','ribeirao pires','T1490','active',null),
('rio grande da serra','rio grande da serra','T1490','active',null),
('salesópolis','salesopolis','T1490','active',null),
('santa isabel','santa isabel','T1490','active',null),
('santo andré','santo andre','T1490','active',null),
('são mateus','sao mateus','T1490','active',null),
('são miguel paulista','sao miguel paulista','T1490','active',null),
('savério','saverio','T1490','active',null),
('vila jacuí','vila jacui','T1490','active',null),
('vila medeiros','vila medeiros','T1490','active',null),
('zona leste','zona leste','T1490','active',null),
('água rasa','agua rasa','T1590','active',null),
('aldeia','aldeia','T1590','active',null),
('alphaville','alphaville','T1590','active',null),
('alto de pinheiros','alto de pinheiros','T1590','active',null),
('anhanguera','anhanguera','T1590','active',null),
('área continental','area continental','T1590','active',null),
('aricanduva','aricanduva','T1590','active',null),
('barra funda','barra funda','T1590','active',null),
('barueri','barueri','T1590','active',null),
('bela vista','bela vista','T1590','active',null),
('belém','belem','T1590','active',null),
('berrini','berrini','T1590','active',null),
('bom retiro','bom retiro','T1590','active',null),
('brás','bras','T1590','active',null),
('brasilândia','brasilandia','T1590','active',null),
('brooklin','brooklin','T1590','active',null),
('butantã','butanta','T1590','active',null),
('caçapava','cacapava','T1590','active',null),
('cachoeirinha','cachoeirinha','T1590','active',null),
('cambuci','cambuci','T1590','active',null),
('campo belo','campo belo','T1590','active',null),
('campo grande','campo grande','T1590','active',null),
('canindé','caninde','T1590','active',null),
('carapicuíba','carapicuiba','T1590','active',null),
('casa verde','casa verde','T1590','active',null),
('chácara santo antônio','chacara santo antonio','T1590','active',null),
('cidade ademar','cidade ademar','T1590','active',null),
('cidade dutra','cidade dutra','T1590','active',null),
('cidade monções','cidade moncoes','T1590','active',null),
('consolação','consolacao','T1590','active',null),
('cursino','cursino','T1590','active',null),
('diadema','diadema','T1590','active',null),
('franco da rocha','franco da rocha','T1590','active',null),
('freguesia do ó','freguesia do o','T1590','active',null),
('guarapiranga','guarapiranga','T1590','active',null),
('guarujá','guaruja','T1590','active',null),
('higienópolis','higienopolis','T1590','active',null),
('iguatemi','iguatemi','T1590','active',null),
('interlagos','interlagos','T1590','active',null),
('ipiranga','ipiranga','T1590','active',null),
('itaim bibi','itaim bibi','T1590','active',null),
('jabaquara','jabaquara','T1590','active',null),
('jaçanã','jacana','T1590','active',null),
('jaguara','jaguara','T1590','active',null),
('jaguaré','jaguare','T1590','active',null),
('jandira','jandira','T1590','active',null),
('jaraguá','jaragua','T1590','active',null),
('jardim américa','jardim america','T1590','active',null),
('jardim ângela','jardim angela','T1590','active',null),
('jardim apura','jardim apura','T1590','active',null),
('jardim belval','jardim belval','T1590','active',null),
('jardim miriam','jardim miriam','T1590','active',null),
('jardim paulista','jardim paulista','T1590','active',null),
('jardim prudência','jardim prudencia','T1590','active',null),
('jardim silveira','jardim silveira','T1590','active',null),
('jardins','jardins','T1590','active',null),
('josé dos campos','jose dos campos','T1590','active',null),
('jurubatuba','jurubatuba','T1590','active',null),
('lapa','lapa','T1590','active',null),
('liberdade','liberdade','T1590','active',null),
('limão','limao','T1590','active',null),
('mairiporã','mairipora','T1590','active',null),
('mandaqui','mandaqui','T1590','active',null),
('moema','moema','T1590','active',null),
('moinho velho','moinho velho','T1590','active',null),
('moóca','mooca','T1590','active',null),
('morumbi','morumbi','T1590','active',null),
('osasco','osasco','T1590','active',null),
('paraibuna','paraibuna','T1590','active',null),
('paranapiacaba','paranapiacaba','T1590','active',null),
('pari','pari','T1590','active',null),
('parque anhembi','parque anhembi','T1590','active',null),
('parque dos bancários','parque dos bancarios','T1590','active',null),
('perdizes','perdizes','T1590','active',null),
('perus','perus','T1590','active',null),
('pinheiros','pinheiros','T1590','active',null),
('pirituba','pirituba','T1590','active',null),
('polvilho','polvilho','T1590','active',null),
('república','republica','T1590','active',null),
('riacho grande','riacho grande','T1590','active',null),
('rio pequeno','rio pequeno','T1590','active',null),
('sacomã','sacoma','T1590','active',null),
('santa cecília','santa cecilia','T1590','active',null),
('santo amaro','santo amaro','T1590','active',null),
('são bernardo do campo','sao bernardo do campo','T1590','active',null),
('são caetano do sul','sao caetano do sul','T1590','active',null),
('são domingos','sao domingos','T1590','active',null),
('são lucas','sao lucas','T1590','active',null),
('são rafael','sao rafael','T1590','active',null),
('sapopemba','sapopemba','T1590','active',null),
('saúde','saude','T1590','active',null),
('sé','se','T1590','active',null),
('taboão','taboao','T1590','active',null),
('tatuapé','tatuape','T1590','active',null),
('terra preta','terra preta','T1590','active',null),
('tucuruvi','tucuruvi','T1590','active',null),
('veleiros','veleiros','T1590','active',null),
('vicente de carvalho','vicente de carvalho','T1590','active',null),
('vila andrade','vila andrade','T1590','active',null),
('vila clarice','vila clarice','T1590','active',null),
('vila clementino','vila clementino','T1590','active',null),
('vila dirce','vila dirce','T1590','active',null),
('vila ester','vila ester','T1590','active',null),
('vila formosa','vila formosa','T1590','active',null),
('vila guilherme','vila guilherme','T1590','active',null),
('vila gumercindo','vila gumercindo','T1590','active',null),
('vila leopoldina','vila leopoldina','T1590','active',null),
('vila maria','vila maria','T1590','active',null),
('vila mariana','vila mariana','T1590','active',null),
('vila mascote','vila mascote','T1590','active',null),
('vila matilde','vila matilde','T1590','active',null),
('vila monte alegre','vila monte alegre','T1590','active',null),
('vila olímpia','vila olimpia','T1590','active',null),
('vila penteado','vila penteado','T1590','active',null),
('vila piauí','vila piaui','T1590','active',null),
('vila prudente','vila prudente','T1590','active',null),
('vila selma','vila selma','T1590','active',null),
('vila sônia','vila sonia','T1590','active',null),
('zona central','zona central','T1590','active',null),
('zona norte','zona norte','T1590','active',null),
('zona oeste','zona oeste','T1590','active',null),
('zona sul','zona sul','T1590','active',null),
('araçariguama','aracariguama','T1690','active',null),
('atibaia','atibaia','T1690','active',null),
('bom jesus dos perdões','bom jesus dos perdoes','T1690','active',null),
('caieiras','caieiras','T1690','active',null),
('cajamar','cajamar','T1690','active',null),
('campo limpo','campo limpo','T1690','active',null),
('capão redondo','capao redondo','T1690','active',null),
('caucaia do alto','caucaia do alto','T1690','active',null),
('cipó-guaçu','cipo-guacu','T1690','active',null),
('cotia','cotia','T1690','active',null),
('cubatão','cubatao','T1690','active',null),
('embu das artes','embu das artes','T1690','active',null),
('embu-guaçu','embu-guacu','T1690','active',null),
('francisco morato','francisco morato','T1690','active',null),
('grajaú','grajau','T1690','active',null),
('itapecerica','itapecerica','T1690','active',null),
('itapecerica da serra','itapecerica da serra','T1690','active',null),
('itapevi','itapevi','T1690','active',null),
('jardim rebouças','jardim reboucas','T1690','active',null),
('jardim são luís','jardim sao luis','T1690','active',null),
('jordanésia','jordanesia','T1690','active',null),
('jundiaí','jundiai','T1690','active',null),
('marsilac','marsilac','T1690','active',null),
('nazaré paulista','nazare paulista','T1690','active',null),
('parelheiros','parelheiros','T1690','active',null),
('pirapora do bom jesus','pirapora do bom jesus','T1690','active',null),
('praia grande','praia grande','T1690','active',null),
('santana de parnaíba','santana de parnaiba','T1690','active',null),
('santos','santos','T1690','active',null),
('são vicente','sao vicente','T1690','active',null),
('taubaté','taubate','T1690','active',null),
('tremembé','tremembe','T1690','active',null),
('vargem grande paulista','vargem grande paulista','T1690','active',null),
('várzea paulista','varzea paulista','T1690','active',null),
('vila pirajussara','vila pirajussara','T1690','active',null),
('itanhaém','itanhaem','T1790','active',null),
('itatiba','itatiba','T1790','active',null),
('itupeva','itupeva','T1790','active',null),
('jarinu','jarinu','T1790','active',null),
('jundiaquara','jundiaquara','T1790','active',null),
('juquitiba','juquitiba','T1790','active',null),
('mairinque','mairinque','T1790','active',null),
('mongaguá','mongagua','T1790','active',null),
('reneville','reneville','T1790','active',null),
('são lourenço da serra','sao lourenco da serra','T1790','active',null),
('são roque','sao roque','T1790','active',null),
('solemar','solemar','T1790','active',null),
('vinhedo','vinhedo','T1790','active',null),
('americana','americana','T1890','active',null),
('araçoiaba da serra','aracoiaba da serra','T1890','active',null),
('campinas','campinas','T1890','active',null),
('pedreira','pedreira','T1890','active',null),
('peruíbe','peruibe','T1890','active',null),
('salto','salto','T1890','active',null),
('socorro','socorro','T1890','active',null),
('sorocaba','sorocaba','T1890','active',null),
('raposo tavares','raposo tavares',null,'human_required','Resultado de rota incompatível; requer validação humana.')
)
insert into catalog.localities
  (canonical_name,normalized_name,pricing_tier_id,status,notes,source_version)
select s.canonical_name,s.normalized_name,p.id,s.status,s.notes,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'
from src s
left join catalog.pricing_tiers p on p.code=s.tier_code
on conflict (normalized_name) do update
set canonical_name=excluded.canonical_name,
    pricing_tier_id=excluded.pricing_tier_id,
    status=excluded.status,
    notes=excluded.notes,
    source_version=excluded.source_version,
    updated_at=now();

with src(locality_norm,alias,normalized_alias) as (
  values
('bras cubas','bras cubas','bras cubas'),
('bras cubas','bdc','bdc'),
('mogi das cruzes','mogi','mogi'),
('sabauna','sabauna','sabauna'),
('aruja','aruja','aruja'),
('biritiba mirim','biritiba-mirim','biritiba-mirim'),
('taiacupeba','taiacupeba','taiacupeba'),
('ferraz de vasconcelos','ferraz','ferraz'),
('guaianases','guianases','guianases'),
('itaquaquecetuba','itaqua','itaqua'),
('poa','poa','poa'),
('santo antonio paulista','santo antonio paulista','santo antonio paulista'),
('vila curuca','vila curuca','vila curuca'),
('cangaiba','cangaiba','cangaiba'),
('carrao','carrao','carrao'),
('cidade lider','cidade lider','cidade lider'),
('igarata','igarata','igarata'),
('jacarei','jacarei','jacarei'),
('jose bonifacio','jose bonifacio','jose bonifacio'),
('maua','maua','maua'),
('nossa senhora do remedio','nossa senhora do remedio','nossa senhora do remedio'),
('ribeirao pires','ribeirao pires','ribeirao pires'),
('salesopolis','salesopolis','salesopolis'),
('santo andre','santo andre','santo andre'),
('sao mateus','sao mateus','sao mateus'),
('sao miguel paulista','sao miguel paulista','sao miguel paulista'),
('saverio','saverio','saverio'),
('vila jacui','vila jacui','vila jacui'),
('agua rasa','agua rasa','agua rasa'),
('area continental','area continental','area continental'),
('belem','belem','belem'),
('bras','bras','bras'),
('brasilandia','brasilandia','brasilandia'),
('butanta','butanta','butanta'),
('cacapava','cacapava','cacapava'),
('caninde','caninde','caninde'),
('carapicuiba','carapicuiba','carapicuiba'),
('chacara santo antonio','chacara santo antonio','chacara santo antonio'),
('cidade moncoes','cidade moncoes','cidade moncoes'),
('consolacao','consolacao','consolacao'),
('freguesia do o','freguesia do o','freguesia do o'),
('guaruja','guaruja','guaruja'),
('higienopolis','higienopolis','higienopolis'),
('jacana','jacana','jacana'),
('jaguare','jaguare','jaguare'),
('jaragua','jaragua','jaragua'),
('jardim america','jardim america','jardim america'),
('jardim angela','jardim angela','jardim angela'),
('jardim apura','apura','apura'),
('jardim prudencia','jardim prudencia','jardim prudencia'),
('jose dos campos','jose dos campos','jose dos campos'),
('limao','limao','limao'),
('mairipora','mairipora','mairipora'),
('mooca','mooca','mooca'),
('parque anhembi','anhembi','anhembi'),
('parque dos bancarios','parque dos bancarios','parque dos bancarios'),
('republica','republica','republica'),
('sacoma','sacoma','sacoma'),
('santa cecilia','santa cecilia','santa cecilia'),
('sao bernardo do campo','sao bernardo do campo','sao bernardo do campo'),
('sao bernardo do campo','sbc','sbc'),
('sao caetano do sul','caetano','caetano'),
('sao domingos','sao domingos','sao domingos'),
('sao lucas','sao lucas','sao lucas'),
('sao rafael','rafael','rafael'),
('saude','saude','saude'),
('taboao','taboao','taboao'),
('tatuape','tatuape','tatuape'),
('vila clementino','clementino','clementino'),
('vila ester','ester','ester'),
('vila formosa','formosa','formosa'),
('vila guilherme','guilherme','guilherme'),
('vila matilde','matilde','matilde'),
('vila olimpia','olimpia','olimpia'),
('vila piaui','vila piaui','vila piaui'),
('vila prudente','prudente','prudente'),
('vila selma','selma','selma'),
('vila sonia','sonia','sonia'),
('aracariguama','aracariguama','aracariguama'),
('bom jesus dos perdoes','bom jesus dos perdoes','bom jesus dos perdoes'),
('capao redondo','capao redondo','capao redondo'),
('cipo-guacu','cipo-guacu','cipo-guacu'),
('cipo-guacu','cipo guacu','cipo guacu'),
('cubatao','cubatao','cubatao'),
('embu-guacu','embu-guacu','embu-guacu'),
('embu-guacu','embu guacu','embu guacu'),
('grajau','grajau','grajau'),
('jardim reboucas','reboucas','reboucas'),
('jardim sao luis','jardim sao luis','jardim sao luis'),
('jordanesia','jordanesia','jordanesia'),
('jundiai','jundiai','jundiai'),
('nazare paulista','nazare','nazare'),
('santana de parnaiba','santana de parnaiba','santana de parnaiba'),
('sao vicente','sao vicente','sao vicente'),
('taubate','taubate','taubate'),
('tremembe','tremembe','tremembe'),
('vargem grande paulista','vargem','vargem'),
('varzea paulista','varzea paulista','varzea paulista'),
('itanhaem','itanhaem','itanhaem'),
('mongagua','mongagua','mongagua'),
('sao lourenco da serra','sao lourenco da serra','sao lourenco da serra'),
('sao roque','sao roque','sao roque'),
('aracoiaba da serra','aracoiaba da serra','aracoiaba da serra'),
('peruibe','peruibe','peruibe')
)
insert into catalog.locality_aliases
  (locality_id,alias,normalized_alias,active,source_version)
select l.id,s.alias,s.normalized_alias,true,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS_META_AI'
from src s
join catalog.localities l on l.normalized_name=s.locality_norm
on conflict (normalized_alias) do update
set locality_id=excluded.locality_id,
    alias=excluded.alias,
    active=true,
    source_version=excluded.source_version;

insert into catalog.commercial_rules
  (rule_key,rule_version,rule_value,source_version)
values
  ('card_surcharge_rate','2026-10-05','{"rate":0.18}'::jsonb,'fase0-v1.2.1/02_REGRAS_COMERCIAIS_E_PROMOCOES'),
  ('card_round_up','2026-10-05','{"multiple":10,"mode":"ceil"}'::jsonb,'fase0-v1.2.1/01_BASE_OFICIAL_LOCALIDADES_E_PRECOS'),
  ('combo_second_main_discount','2026-10-05','{"discount_rate":0.50,"main_services_exactly":2,"same_event_date_time":true}'::jsonb,'fase0-v1.2.1/02_REGRAS_COMERCIAIS_E_PROMOCOES'),
  ('short_term_promotion','2026-10-05','{"max_days":30,"pix_discount":190,"apply_before_combo_and_card":true}'::jsonb,'fase0-v1.2.1/02_REGRAS_COMERCIAIS_E_PROMOCOES'),
  ('followup_auto','2026-10-05','{"delay_hours":23,"max_auto_count":1,"discount_allowed":false}'::jsonb,'fase0-v1.2.1/02_REGRAS_COMERCIAIS_E_PROMOCOES'),
  ('album_addon_price','2026-10-05','{"pix":300}'::jsonb,'fase0-v1.2.1/02_REGRAS_COMERCIAIS_E_PROMOCOES'),
  ('album_gift','2026-10-05','{"commercial_value":300,"min_months":4,"event_types":["casamento","debutante","aniversario"],"only_authorized_gift":true}'::jsonb,'fase0-v1.2.1/02_REGRAS_COMERCIAIS_E_PROMOCOES'),
  ('pix_payment','2026-10-05','{"options":[{"signal_percent":100},{"signal_percent":50,"remaining_percent":50,"remaining_at":"event"}]}'::jsonb,'fase0-v1.2.1/02_REGRAS_COMERCIAIS_E_PROMOCOES')
on conflict (rule_key,rule_version) do update
set rule_value=excluded.rule_value,
    source_version=excluded.source_version;
